apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: cron-check
spec:
  type: bindings.cron
  version: v1
  metadata:
    - name: schedule
      value: "0 0 9 * * *"
scopes:
  - subscription-api
